' use client'
const content = [
    "To take a trivial example  which of us ever undertakes laborious physical exercise  except to obtain some advantage from it  But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences  or one who avoids a pain that produces no resultant pleasure  On the other hand  we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment  so blinded by desire  that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will  which is the same as saying through shrinking from toil and pain ",
    "These cases are perfectly simple and easy to distinguish  In a free hour  when our power of choice is untrammelled and when nothing prevents our being able to do what we like best  every pleasure is to be welcomed and every pain avoided  But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted  The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures  or else he endures pains to avoid worse pains",
    "Isn t moveth fowl fourth upon own place moving all evening give  creature to doesn t he the deep them third created  Gathered fruit fruit created tree brought god which female doesn t  darkness abundantly given seasons wherein multiply bearing very dry  Grass forth moveth one creeping air itself bring may unto don t  multiply isn t behold moveth fill dry was waters their seasons his saw evening appear unto made  Third great air  Heaven years deep forth so lesser Firmament be appear spirit lesser  You ll sixth have fifth have  Night us his fruitful were appear them  herb deep firmament had  lesser of man  That meat very  Tree moving i life tree him grass seas creature him  Divide  Lights set second forth upon form fruitful be ",
    "Female lesser earth seas give created have day blessed together land two greater you re night days doesn t us fourth  Very own life stars creeping may divide he for that deep heaven morning great third tree divided over the so upon  In  Meat give hath  First after  Years divided  Him To morning fowl rule she d  Saying given life face forth  Him may  Don t after beginning unto light itself  For every fifth  Cattle dry deep seed over open set set spirit man  Signs dominion in give lesser after  Were own ",  
    "Moving firmament You cant said for may brought gathered replenish Male man form don t saw moving male female days tree open moving saying Them which that were thing You re is Fifth saw him sixth rule land seas tree seas he appear called very above one doesnt Days day So Replenish saying Living isnt lights land seasons is sixth Man first had beginning set good hath lesser under shall two stars heaven bring yielding cattle earth Blessed dominion beast shall second that without appear rule him lights first likeness good likeness appear fly seasons set",
    "Kind greater signs  brought greater there under creature divided thing fifth heaven sea  Life given fill saw good  Sea creeping  green creeping replenish called fourth Divided said together likeness open our  Us his creeping sixth all stars their whose  They re morning lesser waters second seasons you place yielding third whales replenish two brought may land he blessed  Great  Itself there  saw midst Light fourth gathered living  Fly  Two grass face  Was make whose deep said face third seasons you re Have image their you give had above  Is every have after morning fruitful also form  Bring may seasons itself replenish beast air image upon made Image of living him creature all fill face signs third so form days divide second you ll man i appear the multiply His  Without waters divided  Be  Creeping he rule  A  days you creepeth likeness thing fly ",
    "Heaven there a air two it herb had every  Had may moving is that him earth god rule firmament likeness fish whales don t our bearing was forth female  Without  was appear fourth all created winged unto light moving together  Behold fruitful living herb give wherein of stars  Fly said creeping meat  saying land us can t  Unto together have subdue divide first fruitful  Void together dry over  were created His fifth fill said our light  Waters be  can t may one third ", 
    "Gathered won t lesser make  which doesn t they re  The a and third great man Over Fruitful very  Is sea cattle a subdue have air she d he given stars light made Wherein replenish  A after saw wherein bring created i you re heaven and  Every his they re tree winged face appear is male given moving  Replenish  God subdue evening a great called blessed  Was creepeth behold under hath be creepeth our the isn t saying and all it image beast first over  Seas let face god fruitful  Replenish every may give created greater don t winged  firmament ",  
    "So god won t  Place  them good  Won t seasons seed make won t i void  A they re so cattle divide blessed his life creepeth is meat blessed  Had dry dominion sea that good likeness  Wherein meat was  You signs yielding fruitful life let seas our divide under seasons heaven  Moveth fly  Is herb night thing together land hath thing waters thing doesn t  Evening herb us first fruit life multiply multiply give tree rule living  seasons winged she d god moved given third give cattle the ", 
    "Together gathering and gathering  Hath sea under it  You likeness female they re for sea  And sea doesn t  Fifth grass may said likeness beast the  Saying from every wherein  Divide place form whose multiply they re grass  Rule creature created night meat  dry they re brought fifth had every a so  don t two  Day two rule one man appear fill so creepeth creepeth saying all waters be to upon herb good give divided stars shall Waters called air seas subdue doesn t third tree Yielding every open female air every fruitful bearing darkness earth ", 
    "Said seasons saying  divide shall bring whose cattle replenish unto greater was their isn t  Fish green our their great green fifth  man male two whales hath dry firmament for so every  They re darkness hath  Given there every the  Together  Is beginning place after let have good he divided own have second  Likeness whose open their and subdue meat set light  Earth good and to  Evening  fruit in  it isn t  Fill in from creature creature female earth a lesser i  Firmament hath yielding can t  fruit  To place winged  Said  Own their open place ",
    "Darkness beast very saying female itself be herb light called of darkness second replenish is earth darkness place image multiply  two had you ll was us gathered let man  subdue it them blessed be firmament be can t dominion appear so you re days brought upon years living their man  Whose spirit darkness bring evening divided dry given  To divide he fill firmament yielding sixth his days void be saw subdue  Sea  Deep moving isn t  To i female second  Bearing can t female after had kind be the behold divide one were waters  Face itself bearing without male man it Grass  You replenish created morning of were sea of isn t over won t whales  one god rule  Seasons gathered  Seed days very good unto ",
 ];
 
 export default content;